### ISSUE TITLE
notify type in yaml schema should support string AND array

### ISSUE THREAD

**Issue by KMouratidis** [ansible/schemas#195] opened 2022-03-30 13:36 UTC
yaml-schema complains that `notify` should accept a string for this definition:

```
  notify:
    - Restart Docker
    - Restart NFS
```

It seems the definition is:

```
"notify": {
    "title": "Notify",
    "type": "string"
},
```

But (maybe) it should be:

```
"notify": {
    "title": "Notify",
    "anyOf": [
        {
            "type": "string"
        },
        {
            "type": "array"
        }
    ]
},
```

First raised [here](https://github.com/ansible/vscode-ansible/issues/466).

**Comment by ziegenberg** [comment] 2022-03-30 15:19
Hi @KMouratidis,

can you check if this behaviour still can be reproduced? This issue is most certainly a duplicate of #184 and was fixed two days ago in #188. It should work by now.

**Closed** 2022-03-30 15:22 UTC
Labels: duplicate
